//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.13 at 11:27:13 AM IST 
//


package com.mkyong;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrikbordItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrikbordItem">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="itemId" type="{}int11" minOccurs="0"/>
 *         &lt;element name="title" type="{}string30"/>
 *         &lt;element name="description" type="{}string100" minOccurs="0"/>
 *         &lt;element name="prikbordId" type="{}int11" minOccurs="0"/>
 *         &lt;element name="parentId" type="{}int11"/>
 *         &lt;element name="parentalRating" type="{}string10" minOccurs="0"/>
 *         &lt;element name="posterFile" type="{}string100" minOccurs="0"/>
 *         &lt;element name="reference" type="{}string100" minOccurs="0"/>
 *         &lt;element name="referenceType" type="{}ReferenceType"/>
 *         &lt;element name="folderType" type="{}FolderType" minOccurs="0"/>
 *         &lt;element name="contentType" type="{}ContentType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrikbordItem", propOrder = {
    "itemId",
    "title",
    "description",
    "prikbordId",
    "parentId",
    "parentalRating",
    "posterFile",
    "reference",
    "referenceType",
    "folderType",
    "contentType"
})
public class PrikbordItem {

    protected Integer itemId;
    @XmlElement(required = true)
    protected String title;
    protected String description;
    protected Integer prikbordId;
    protected int parentId;
    protected String parentalRating;
    protected String posterFile;
    protected String reference;
    @XmlElement(required = true)
    protected ReferenceType referenceType;
    protected FolderType folderType;
    protected ContentType contentType;

    /**
     * Gets the value of the itemId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * Sets the value of the itemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setItemId(Integer value) {
        itemId = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        title = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        description = value;
    }

    /**
     * Gets the value of the prikbordId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPrikbordId() {
        return prikbordId;
    }

    /**
     * Sets the value of the prikbordId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPrikbordId(Integer value) {
        prikbordId = value;
    }

    /**
     * Gets the value of the parentId property.
     * 
     */
    public int getParentId() {
        return parentId;
    }

    /**
     * Sets the value of the parentId property.
     * 
     */
    public void setParentId(int value) {
        parentId = value;
    }

    /**
     * Gets the value of the parentalRating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentalRating() {
        return parentalRating;
    }

    /**
     * Sets the value of the parentalRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentalRating(String value) {
        parentalRating = value;
    }

    /**
     * Gets the value of the posterFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosterFile() {
        return posterFile;
    }

    /**
     * Sets the value of the posterFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosterFile(String value) {
        posterFile = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReference(String value) {
        reference = value;
    }

    /**
     * Gets the value of the referenceType property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getReferenceType() {
        return referenceType;
    }

    /**
     * Sets the value of the referenceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setReferenceType(ReferenceType value) {
        referenceType = value;
    }

    /**
     * Gets the value of the folderType property.
     * 
     * @return
     *     possible object is
     *     {@link FolderType }
     *     
     */
    public FolderType getFolderType() {
        return folderType;
    }

    /**
     * Sets the value of the folderType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FolderType }
     *     
     */
    public void setFolderType(FolderType value) {
        folderType = value;
    }

    /**
     * Gets the value of the contentType property.
     * 
     * @return
     *     possible object is
     *     {@link ContentType }
     *     
     */
    public ContentType getContentType() {
        return contentType;
    }

    /**
     * Sets the value of the contentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentType }
     *     
     */
    public void setContentType(ContentType value) {
        contentType = value;
    }

}
