//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.13 at 11:27:13 AM IST 
//


package com.mkyong;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrikbordData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrikbordData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="prikbordId" type="{}int11"/>
 *         &lt;element name="title" type="{}string30" minOccurs="0"/>
 *         &lt;element name="parentalRating" type="{}string10" minOccurs="0"/>
 *         &lt;element name="posterFile" type="{}string100" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrikbordData", propOrder = {
    "prikbordId",
    "title",
    "parentalRating",
    "posterFile"
})
public class PrikbordData {

    protected int prikbordId;
    protected String title;
    protected String parentalRating;
    protected String posterFile;

    /**
     * Gets the value of the prikbordId property.
     * 
     */
    public int getPrikbordId() {
        return prikbordId;
    }

    /**
     * Sets the value of the prikbordId property.
     * 
     */
    public void setPrikbordId(int value) {
        prikbordId = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        title = value;
    }

    /**
     * Gets the value of the parentalRating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentalRating() {
        return parentalRating;
    }

    /**
     * Sets the value of the parentalRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentalRating(String value) {
        parentalRating = value;
    }

    /**
     * Gets the value of the posterFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosterFile() {
        return posterFile;
    }

    /**
     * Sets the value of the posterFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosterFile(String value) {
        posterFile = value;
    }

}
