//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.13 at 11:27:13 AM IST 
//


package com.mkyong;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReferenceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReferenceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="VOD"/>
 *     &lt;enumeration value="NPVR"/>
 *     &lt;enumeration value="PPV"/>
 *     &lt;enumeration value="Unmanaged"/>
 *     &lt;enumeration value="Folder"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReferenceType")
@XmlEnum
public enum ReferenceType {

    VOD("VOD"),
    NPVR("NPVR"),
    PPV("PPV"),
    @XmlEnumValue("Unmanaged")
    UNMANAGED("Unmanaged"),
    @XmlEnumValue("Folder")
    FOLDER("Folder");
    private final String value;

    ReferenceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReferenceType fromValue(String v) {
        for (ReferenceType c: ReferenceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
