EBG="undefined"!=typeof EBG?EBG:{};EBG.Light=EBG.Light||{};EBG.Light.Infra=function(){};EBG.Light.Infra.isDefined=function(a){return"undefined"!=typeof a};EBG.Light.Infra.getTimestamp=function(){var a=new Date;return parseInt(a.getHours()+1)+":"+a.getMinutes()+":"+a.getSeconds()+"."+a.getMilliseconds()+" "+a.getDate()+"."+parseInt(a.getMonth()+1)+"."+a.getFullYear()};
EBG.Light.Infra.getUrlParameter=function(a){var b="",c=EBG.Light.Infra.getWindowLocation().toString(),d=RegExp("[&,?]"+a+"=(.*)$","i");if((a=c.match(RegExp("[&,?]"+a+"=(.*)[&]","i"))||c.match(d))&&0<a.length)-1<a[1].indexOf("&")&&(a[1]=a[1].substr(0,a[1].indexOf("&"))),b=a[1];return b};EBG.Light.Infra.combinePaths=function(a,b){a=a||"";b=b||"";a&&"/"!=a[a.length-1]&&(a+="/");var c=a;b&&(c+=b);return c};
EBG.Light.Infra.isPageLoaded=function(){var a=!0;"complete"!=document.readyState&&"loaded"!=document.readyState&&"interactive"!=document.readyState&&(a=!1);return a};EBG.Light.Infra.addChildToPage=function(a,b){if("undefined"==typeof b||!b)b=document.body||document.getElementsByTagName("head")[0];b.appendChild(a)};EBG.Light.Infra.createScriptElement=function(a,b,c,d){try{var e=a.createElement(b);e.type=c;e.src=d;e.async=!1;return e}catch(g){}};
EBG.Light.Infra.addScriptElement=function(a,b){var c;if(b){if(c=b,0==c.childNodes.length){var d=document.createElement("div");d.style.display="none";b.appendChild(d)}}else c=document.head||document.documentElement;c.insertBefore(a,c.firstChild)};EBG.Light.Infra.getWindowLocation=function(){return window.location};EBG.Light.Infra.getRandomNumber=function(){try{var a=Math.random().toString();return a=a.substr(a.indexOf(".")+1)}catch(b){}};
EBG.Light.Infra.getAddInEyeDomain=function(a){var b="",c="",d=0,a=(a?a:window).document,a=a.referrer?a.referrer:a.location.href;try{a=a.toLowerCase(),7<=a.length&&"http://"==a.substr(0,7)?(c=a.substr(7),a.substr(0,7)):8<=a.length&&"https://"==a.substr(0,8)?(c=a.substr(8),a.substr(0,8)):c=a,d=c.indexOf("/"),0<d&&(c=c.substr(0,d)),b=c}catch(e){b=""}return b};
EBG.Light.Infra.createFriendlyIframe=function(a,b,c,d){a=(a?a:document).createElement("iframe");b&&a.setAttribute("id",b);a.style.display=c?"":"none";a.style.width=c?c+"px":"0px";a.style.height=d?d+"px":"0px";document.documentMode&&8>document.documentMode?(a.frameBorder=0,a.margin=0,a.marginWidth=0,a.marginHeight=0,a.scrolling="no"):(a.setAttribute("scrolling","no"),a.setAttribute("marginwidth","0"),a.setAttribute("marginheight","0"),a.setAttribute("frameborder","0"));return a};
EBG.Light.Infra.writeToFriendlyIframe=function(a,b,c){var c=this.isDefined(c)?c:!1,d;d=a.contentWindow?a.contentWindow.document:a.contentDocument&&a.contentDocument.document?a.contentDocument.document:a.contentDocument;d.write(b);c&&setTimeout(function(){d.close()},1E3)};
EBG.Light.Infra.createUnfriendlyIframe=function(a,b){if(b&&!EBG.Light.Infra.isPageLoaded())this.logger&&this.logger.info("Adding unfriendly iframe in sync mode, url: "+a),document.write('<iframe src="'+a+'" style="display:none;width:0px;height:0px"></iframe>');else{this.logger&&this.logger.info("Adding unfriendly iframe in async mode, url: "+a);var c=document.createElement("iframe");c.setAttribute("src",a);c.style.display="none";EBG.Light.Infra.addChildToPage(c)}};
EBG.Light.Infra.getTopLevelReferrer=function(a){var b=null;try{a.top&&a.top.document&&a.top.document.referrer&&(b=a.top.document.referrer.toString())}catch(c){}return b};EBG.JSON="JSON"in window&&window.JSON&&window.JSON.stringify&&window.JSON.parse?JSON:{};
(function(){function a(a){return 10>a?"0"+a:a}function b(a){e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var b=p[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,d){var e,j,k,n,o=g,h,f=d[a];f&&"object"===typeof f&&"function"===typeof f.toJSON&&(f=f.toJSON(a));"function"===typeof l&&(f=l.call(d,a,f));switch(typeof f){case "string":return b(f);case "number":return isFinite(f)?""+f:"null";case "boolean":case "null":return""+
f;case "object":if(!f)return"null";g+=m;h=[];if("[object Array]"===Object.prototype.toString.apply(f)){n=f.length;for(e=0;e<n;e+=1)h[e]=c(e,f)||"null";k=0===h.length?"[]":g?"[\n"+g+h.join(",\n"+g)+"\n"+o+"]":"["+h.join(",")+"]";g=o;return k}if(l&&"object"===typeof l){n=l.length;for(e=0;e<n;e+=1)j=l[e],"string"===typeof j&&(k=c(j,f))&&h.push(b(j)+(g?": ":":")+k)}else for(j in f)Object.hasOwnProperty.call(f,j)&&(k=c(j,f))&&h.push(b(j)+(g?": ":":")+k);k=0===h.length?"{}":g?"{\n"+g+h.join(",\n"+g)+"\n"+
o+"}":"{"+h.join(",")+"}";g=o;return k}}if("function"!==typeof Date.prototype.toJSON)Date.prototype.toJSON=function(){return this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z"},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,g,m,p={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},l;if("function"!==typeof EBG.JSON.stringify)EBG.JSON.stringify=function(a,b,d){var e;m=g="";if("number"===typeof d)for(e=0;e<d;e+=1)m+=" ";else"string"===typeof d&&(m=d);if((l=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("EBG.JSON.stringify");
return c("",{"":a})};if("function"!==typeof EBG.JSON.parse)EBG.JSON.parse=function(a,b){function c(a,d){var e,g,f=a[d];if(f&&"object"===typeof f)for(e in f)Object.hasOwnProperty.call(f,e)&&(g=c(f,e),void 0!==g?f[e]=g:delete f[e]);return b.call(a,d,f)}var e;d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof b?c({"":e},""):e;throw new SyntaxError("EBG.JSON.parse");}})();EBG.BrowserDetector=function(){this.browserName=navigator.appName;this.fullVersion=""+parseFloat(navigator.appVersion);this.majorVersion=parseInt(navigator.appVersion,10);this._init()};EBG.BrowserDetector.Browser={InternetExplorer:"InternetExplorer",Chrome:"Chrome",Firefox:"Firefox",Opera:"Opera",Safari:"Safari"};
EBG.BrowserDetector.prototype={_init:function(){var a=navigator.userAgent,b,c;if(-1!=(c=a.indexOf("Opera"))){if(this.browserName=EBG.BrowserDetector.Browser.Opera,this.fullVersion=a.substring(c+6),-1!=(c=a.indexOf("Version")))this.fullVersion=a.substring(c+8)}else if(-1!=(c=a.indexOf("MSIE")))this.browserName=EBG.BrowserDetector.Browser.InternetExplorer,this.fullVersion=a.substring(c+5);else if(-1!=(c=a.indexOf("Chrome")))this.browserName=EBG.BrowserDetector.Browser.Chrome,this.fullVersion=a.substring(c+
7);else if(-1!=(c=a.indexOf("Safari"))){if(this.browserName=EBG.BrowserDetector.Browser.Safari,this.fullVersion=a.substring(c+7),-1!=(c=a.indexOf("Version")))this.fullVersion=a.substring(c+8)}else if(-1!=(c=a.indexOf("Firefox")))this.browserName=EBG.BrowserDetector.Browser.Firefox,this.fullVersion=a.substring(c+8);else if((b=a.lastIndexOf(" ")+1)<(c=a.lastIndexOf("/")))if(this.browserName=a.substring(b,c),this.fullVersion=a.substring(c+1),this.browserName.toLowerCase()==this.browserName.toUpperCase())this.browserName=
navigator.appName;if(-1!=(a=this.fullVersion.indexOf(";")))this.fullVersion=this.fullVersion.substring(0,a);if(-1!=(a=this.fullVersion.indexOf(" ")))this.fullVersion=this.fullVersion.substring(0,a);this.majorVersion=parseInt(""+this.fullVersion,10);if(isNaN(this.majorVersion))this.fullVersion=""+parseFloat(navigator.appVersion),this.majorVersion=parseInt(navigator.appVersion,10)}};EBG.Light.Logger=function(a){this._level=a;this.startNestingGroupNames=[];this.endNestingGroupNames=[]};
EBG.Light.Logger.DebugMode="mmdebug";EBG.Light.Logger.LoggerLevels={NONE:0,ERROR:1,INFO:2,WARN:3,DEBUG:4};
EBG.Light.Logger.prototype={setLevel:function(a){this._level=a},timestamp:!1,debug:function(a){this._reportToLog(EBG.Light.Logger.LoggerLevels.DEBUG,arguments)},info:function(a){this._reportToLog(EBG.Light.Logger.LoggerLevels.INFO,arguments)},warn:function(a){this._reportToLog(EBG.Light.Logger.LoggerLevels.WARN,arguments)},error:function(a){this._reportToLog(EBG.Light.Logger.LoggerLevels.ERROR,arguments)},exception:function(a,b){var c="string"!==b?this._format("Exception in {0}. message: {1}",a,b.message):
this._format("Exception in: {0}. message: {1}",a,b);b.stack&&(c+=this._format(" stack: {0}",b.stack));this._reportToLog(EBG.Light.Logger.LoggerLevels.ERROR,[c])},startGroup:function(a){this._supportNesting()&&this.startNestingGroupNames.push(a)},endGroup:function(){this._supportNesting()&&0<this.endNestingGroupNames.length&&window.console.groupEnd(this.endNestingGroupNames.pop())},_consoleAvailable:function(){try{return void 0!==window&&void 0!==window.console}catch(a){return!1}},_supportNesting:function(){return this._consoleAvailable()?
void 0!==window.console.group:!1},_supportErrorMessage:function(){return void 0!==window.console.error},_supportInfoMessage:function(){return void 0!==window.console.info||void 0!==window.opera},_supportWarnMessage:function(){return void 0!==window.console.warn||void 0!==window.opera},_supportObjectView:function(){return void 0!==window.console.dir||void 0!==window.opera},_callConsoleFunction:function(a,b){var c=!1;switch(a){case EBG.Light.Logger.LoggerLevels.INFO:this._supportInfoMessage()&&(window.console.info(b),
c=!0);break;case EBG.Light.Logger.LoggerLevels.WARN:this._supportWarnMessage()&&(window.console.warn(b),c=!0);break;case EBG.Light.Logger.LoggerLevels.ERROR:this._supportErrorMessage()&&(consoleFunction=window.console.error(b),c=!0)}c||window.console.log(b)},_format:function(a){for(var b=1;b<arguments.length;b++)a=a.replace(RegExp("\\{"+(b-1)+"\\}","gi"),""+arguments[b]);return a},_getTimestamp:function(){if(this.timestamp)return EBG.Light.Infra.getTimestamp()},_reportToLog:function(a,b){if(this._level>=
a&&this._consoleAvailable()){var c=b[0];"[object String]"!==Object.prototype.toString.call(c)?this._supportObjectView()||(c=c.toString()):c=this._format.apply(null,b);this.timestamp&&"[object String]"===Object.prototype.toString.call(c)&&(c=this._getTimestamp()+": "+c);if(void 0===window.opera){for(;this.startNestingGroupNames.length;)window.console.group(this.startNestingGroupNames[0]),this.endNestingGroupNames.push(this.startNestingGroupNames.shift());this._callConsoleFunction(a,c)}else opera.postError(c)}}};
EBG.ServerCommunicator=function(a){this.logger=a;this._browserDetector=new EBG.BrowserDetector;this._urlReportTimeout=100;this._imgArr=[];for(i=0;10>i;i++)this._imgArr.push(new Image)};
EBG.ServerCommunicator.prototype={raiseServerCall:function(a,b,c){a=this._addParamToBsURL(a,EBG.OneTagEnum.UrlParamNames.NO_AJAX,"1");this._scriptTag(a,b,c)},reportUrlsList:function(a){for(var b=0;b<this._imgArr.length;b++)this.reportUrl(a,this._imgArr[b])},reportUrl:function(a,b){if(0<a.length){var c=this,d=a.shift();b.onload=b.onerror=function(){c.reportUrl(a,b)};b.src=d;this.logger&&this.logger.info("Reporting URL "+d)}},_scriptTag:function(a,b,c){if(c)document.write("<script src='"+a+"'><\/script>");
else{var d=document.createElement("script");d.type="text/"+(a.type||"javascript");d.src=a.src||a;d.async=!0;d.onreadystatechange=d.onload=function(){var a=d.readyState;if(b&&!b.done&&(!a||/loaded|complete/.test(a)))b.done=!0,b(bsResponse)};this.logger&&this.logger.info("Scripted server call: "+a);EBG.Light.Infra.addChildToPage(d)}},_addParamToBsURL:function(a,b,c){return-1!=a.indexOf("?")?a+"&"+b+"="+c:a+"?"+b+"="+c}};EBG.OneTagEnum=function(){};
EBG.OneTagEnum.UrlParamNames={ID:"onetagid",DISP_TYPE:"dispType",SYNC:"sync",ONETAG_URL:"ebOneTagURL",PAGE_URL:"pageurl",NO_AJAX:"noAjax",DEBUG_MODE:"debugmode",NO_SCRIPT:"ns",MOBILE:"mb",ACTIVITY_PARAMS:"activityValues",RETARGET_PARAMS:"retargetingValues",DYNAMIC_RETARGET_PARAMS:"dynamicRetargetingValues",CONDITIONAL_PARAMS:"acp",RANDOM:"rnd"};EBG.OneTagEnum.DisplayTypes={IFRAME:"iframe",JAVASCRIPT:"js"};EBG.OneTagEnum.HttpProtocol={HTTP:"http",HTTPS:"https"};EBG.OneTagLogger=function(){};
EBG.OneTag=function(){this.logNeeded=EBG.Light.Infra.getUrlParameter(EBG.Light.Logger.DebugMode)?1:0;this.oneTagLogger=new EBG.Light.Logger(EBG.Light.Infra.getUrlParameter(EBG.Light.Logger.DebugMode));this.oneTagLogger.timestamp=!0;this.serverCommunicator=this.serverCommunicator||new EBG.ServerCommunicator(this.oneTagLogger);this._oneTagObj=null;if(EBG.Light.Infra.isDefined(window.versaTag))this._oneTagObj=versaTag};
EBG.OneTag.prototype={generateRequest:function(a){if(this._oneTagObj)if(this.oneTagLogger.info("One Tag Started"),a=this._generateBsURL(this._oneTagObj,a),this.oneTagLogger.info("Server URL: "+a),this._oneTagObj.dispType.toLowerCase()==EBG.OneTagEnum.DisplayTypes.IFRAME)EBG.Light.Infra.createUnfriendlyIframe(a,this._oneTagObj.sync);else{var b=this;this.serverCommunicator.raiseServerCall(a,function(a){b._handleResponse(a)},1==this._oneTagObj.sync)}},setActivityParam:function(a,b){if(!this._oneTagObj.activityParams)this._oneTagObj.activityParams=
{};this._oneTagObj.activityParams[a]=b},getActivityParam:function(a){var b=null;this._oneTagObj.activityParams&&this._oneTagObj.activityParams[a]&&(b=this._oneTagObj.activityParams[a]);return b},clearActivityParam:function(){this._oneTagObj.activityParams={}},setRetargetParam:function(a,b){if(!this._oneTagObj.retargetParams)this._oneTagObj.retargetParams={};this._oneTagObj.retargetParams[a]=b},getRetargetParam:function(a){var b=null;this._oneTagObj.retargetParams&&this._oneTagObj.retargetParams[a]&&
(b=this._oneTagObj.retargetParams[a]);return b},clearRetargetParam:function(){this._oneTagObj.retargetParams={}},setDynamicRetargetParam:function(a,b){if(!this._oneTagObj.dynamicRetargetParams)this._oneTagObj.dynamicRetargetParams={};this._oneTagObj.dynamicRetargetParams[a]=b},getDynamicRetargetParam:function(a){var b=null;this._oneTagObj.dynamicRetargetParams&&this._oneTagObj.dynamicRetargetParams[a]&&(b=this._oneTagObj.dynamicRetargetParams[a]);return b},clearDynamicRetargetParam:function(){this._oneTagObj.dynamicRetargetParams=
{}},setConditionalParam:function(a,b){if(!this._oneTagObj.conditionalParams)this._oneTagObj.conditionalParams={};this._oneTagObj.conditionalParams[a]=b},getConditionalParam:function(a){var b=null;this._oneTagObj.conditionalParams&&this._oneTagObj.conditionalParams[a]&&(b=this._oneTagObj.conditionalParams[a]);return b},clearConditionalParam:function(){this._oneTagObj.conditionalParams={}},_generateBsURL:function(a,b){var c=this._getProtocol(a.ptcl)+a.bsUrl+"?cn=ot&"+EBG.OneTagEnum.UrlParamNames.ID+
"="+a.id+"&"+EBG.OneTagEnum.UrlParamNames.DISP_TYPE+"="+a.dispType+"&"+EBG.OneTagEnum.UrlParamNames.SYNC+"="+a.sync;a.mobile&&(c+="&"+EBG.OneTagEnum.UrlParamNames.MOBILE+"="+a.mobile);b=b?escape(b):escape(EBG.Light.Infra.getWindowLocation());c+="&"+EBG.OneTagEnum.UrlParamNames.PAGE_URL+"=$$"+b+"$$";c+=this._prepareParamUrl(a.activityParams,EBG.OneTagEnum.UrlParamNames.ACTIVITY_PARAMS);c+=this._prepareParamUrl(a.retargetParams,EBG.OneTagEnum.UrlParamNames.RETARGET_PARAMS);c+=this._prepareParamUrl(a.conditionalParams,
EBG.OneTagEnum.UrlParamNames.CONDITIONAL_PARAMS);c+=this._prepareParamUrl(a.dynamicRetargetParams,EBG.OneTagEnum.UrlParamNames.DYNAMIC_RETARGET_PARAMS);a.dispType.toLowerCase()==EBG.OneTagEnum.DisplayTypes.IFRAME&&(c+="&"+EBG.OneTagEnum.UrlParamNames.ONETAG_URL+"="+escape(document.getElementById("ebOneTagUrlId").src));this.logNeeded&&(c+="&"+EBG.Light.Logger.DebugMode+"="+this.logNeeded);c+="&"+EBG.OneTagEnum.UrlParamNames.NO_SCRIPT+"=0";c+="&"+EBG.OneTagEnum.UrlParamNames.RANDOM+"="+EBG.Light.Infra.getRandomNumber();
a.debugData&&(c+="&"+a.debugData);var d=EBG.Light.Infra.getTopLevelReferrer(window);d&&(c+="&referrer="+d);return c},_prepareParamUrl:function(a,b){var c=!0,d="",e;for(e in a)null!=a[e]&&""!=a[e]&&(c?(d+="&"+b+"=$$"+e+"="+a[e],c=!1):d+="&"+e+"="+a[e]);c||(d+="$$");return d},_getProtocol:function(a){var b="http://";return b=a&&a.toLowerCase()==EBG.OneTagEnum.HttpProtocol.HTTP?"http://":a&&a.toLowerCase()==EBG.OneTagEnum.HttpProtocol.HTTPS?"https://":"https:"==EBG.Light.Infra.getWindowLocation().protocol?
"https://":"http://"},_handleResponse:function(a){this.oneTagLogger.info("Server response: "+a);if(responseObj=this._deserializeResponse(a))this._handleScriptTags(responseObj.scripts),this._handleUrlTags(responseObj.urls),this._handleCustomScript(responseObj.customScript),this._handleServerMessages(responseObj.logMessages)},_deserializeResponse:function(a){var b;try{this.logNeeded&&-1!=a.indexOf("/*")&&(a=a.substring(0,a.lastIndexOf("/*"))),b=EBG.JSON.parse(unescape(a))}catch(c){this.oneTagLogger.exeption("OneTag._deserializeResponse",
c)}return b},_handleCustomScript:function(a){if(a&&("http:"==a.substring(0,5).toLowerCase()||"https:"==a.substring(0,6).toLowerCase())){var b=document.createElement("script");b.type="text/javascript";b.src=a;EBG.Light.Infra.addScriptElement(b)}},_handleServerMessages:function(a){if(a&&0<a.length){this.oneTagLogger.timestamp=!1;this.oneTagLogger.info("Server Messages:");for(var b=0;b<a.length;b++)a[b]&&this.oneTagLogger.info("  "+a[b]);this.oneTagLogger.timestamp=!0}},_handleScriptTags:function(a){if(a)for(var b=
0;b<a.length;b++)a[b]&&this._injectScripts(a[b])},_handleUrlTags:function(a){a&&this.serverCommunicator.reportUrlsList(a)},_injectScripts:function(a){if(a){a="<html><head></head><body>"+a+"</body></html>";this.oneTagLogger.info("Script Injection: "+a);var b=EBG.Light.Infra.createFriendlyIframe();EBG.Light.Infra.addChildToPage(b);EBG.Light.Infra.writeToFriendlyIframe(b,a,!0)}}};var versaTagObj=new EBG.OneTag;versaTagObj.generateRequest();
