//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.13 at 11:23:35 AM IST 
//


package com.manu.restapi.common.vo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonRootName;


/**
 * General Customer error response.
 * <p>
 * Java class for CustomerErrorResponse complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerErrorResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="ErrorDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerErrorResponse", propOrder = {
    "errorCode",
    "errorDescription"
})
@XmlRootElement(name = "CustomerErrorResponse")
@JsonRootName(value = "CustomerErrorResponse")
public class CustomerErrorResponse {

    @XmlElement(name = "ErrorCode", required = true)
	@JsonProperty(value = "ErrorCode", required = true)
	protected Integer errorCode;
    @XmlElement(name = "ErrorDescription", required = true)
	@JsonProperty(value = "ErrorDescription", required = true)
    protected String errorDescription;

    /**
	 * Gets the value of the errorCode property.
	 * 
	 * @return possible object is {@link Integer }
	 */
	public Integer getErrorCode() {
        return errorCode;
    }

    /**
	 * Sets the value of the errorCode property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 */
	public void setErrorCode(Integer value) {
        errorCode = value;
    }

    /**
     * Gets the value of the errorDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorDescription() {
        return errorDescription;
    }

    /**
     * Sets the value of the errorDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorDescription(String value) {
        errorDescription = value;
    }

}
