package be.belgacom.tv.proxy.auth.services.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import be.belgacom.tv.proxy.auth.services.ws.gen.IDPServicesPortType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MBP-IDPServices-3.1-Service", targetNamespace = "urn:v3.idpservices.mbp.services.bgc", wsdlLocation = "file:/C:/BGC_Code/BEP4.0/authproxy/etc/wsdl/MBP-SVC-IDPServices-3.1-standard-http_binding.wsdl")
public class MBPIDPServices31Service extends Service {

	private final static URL MBPIDPSERVICES31SERVICE_WSDL_LOCATION;
	private final static WebServiceException MBPIDPSERVICES31SERVICE_EXCEPTION;
	private final static QName MBPIDPSERVICES31SERVICE_QNAME = new QName(
			"urn:v3.idpservices.mbp.services.bgc",
			"MBP-IDPServices-3.1-Service");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			// InputStream resourceFileStream =
			// getClass().getClassLoader().getResourceAsStream("/MBP-SVC-IDPServices-3.1-standard-http_binding.wsdl");
			url = new URL(
					"file:WebContent/WEB-INF/wsdl/MBP-SVC-IDPServices-3.1-standard-http_binding.wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		MBPIDPSERVICES31SERVICE_WSDL_LOCATION = url;
		MBPIDPSERVICES31SERVICE_EXCEPTION = e;
	}

	public MBPIDPServices31Service() {
		super(__getWsdlLocation(), MBPIDPSERVICES31SERVICE_QNAME);
	}

/*	public MBPIDPServices31Service(WebServiceFeature... features) {
		super(__getWsdlLocation(), MBPIDPSERVICES31SERVICE_QNAME, features);
	}*/

	public MBPIDPServices31Service(URL wsdlLocation) {
		super(wsdlLocation, MBPIDPSERVICES31SERVICE_QNAME);
	}

/*	public MBPIDPServices31Service(URL wsdlLocation,
			WebServiceFeature... features) {
		super(wsdlLocation, MBPIDPSERVICES31SERVICE_QNAME, features);
	}*/

	public MBPIDPServices31Service(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

/*	public MBPIDPServices31Service(URL wsdlLocation, QName serviceName,
			WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}*/

	/**
	 * 
	 * @return returns IDPServicesPortType
	 */
	@WebEndpoint(name = "MBP-IDPServices-3.1-SOAP-Port")
	public IDPServicesPortType getMBPIDPServices31SOAPPort() {
		return super.getPort(new QName("urn:v3.idpservices.mbp.services.bgc",
				"MBP-IDPServices-3.1-SOAP-Port"), IDPServicesPortType.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns IDPServicesPortType
	 */
	@WebEndpoint(name = "MBP-IDPServices-3.1-SOAP-Port")
	public IDPServicesPortType getMBPIDPServices31SOAPPort(
			WebServiceFeature... features) {
		return super.getPort(new QName("urn:v3.idpservices.mbp.services.bgc",
				"MBP-IDPServices-3.1-SOAP-Port"), IDPServicesPortType.class,
				features);
	}

	private static URL __getWsdlLocation() {
		if (MBPIDPSERVICES31SERVICE_EXCEPTION != null) {
			throw MBPIDPSERVICES31SERVICE_EXCEPTION;
		}
		return MBPIDPSERVICES31SERVICE_WSDL_LOCATION;
	}

}
