<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://services.com" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://services.com" xmlns:intf="http://services.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4
Built on Apr 22, 2006 (06:55:48 PDT)-->
 <wsdl:types>
  <schema elementFormDefault="qualified" targetNamespace="http://services.com" xmlns="http://www.w3.org/2001/XMLSchema">
   <element name="getMessage">
    <complexType/>
   </element>
   <element name="getMessageResponse">
    <complexType>
     <sequence>
      <element name="getMessageReturn" type="xsd:string"/>
     </sequence>
    </complexType>
   </element>
  </schema>
 </wsdl:types>

   <wsdl:message name="getMessageRequest">

      <wsdl:part element="impl:getMessage" name="parameters"/>

   </wsdl:message>

   <wsdl:message name="getMessageResponse">

      <wsdl:part element="impl:getMessageResponse" name="parameters"/>

   </wsdl:message>

   <wsdl:portType name="HelloWorldService">

      <wsdl:operation name="getMessage">

         <wsdl:input message="impl:getMessageRequest" name="getMessageRequest"/>

         <wsdl:output message="impl:getMessageResponse" name="getMessageResponse"/>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="HelloWorldServiceSoapBinding" type="impl:HelloWorldService">

      <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="getMessage">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="getMessageRequest">

            <wsdlsoap:body use="literal"/>

         </wsdl:input>

         <wsdl:output name="getMessageResponse">

            <wsdlsoap:body use="literal"/>

         </wsdl:output>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="HelloWorldServiceService">

      <wsdl:port binding="impl:HelloWorldServiceSoapBinding" name="HelloWorldService">

         <wsdlsoap:address location="http://localhost:8080/webservices/services/HelloWorldService"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
